### ISSUE TITLE
FEAT: [CADT] Provide an easy way to tell if CADT is ready to accept new data after the last Commit

### ISSUE THREAD

**Issue by fizpawiz** [Chia-Network/cadt#968]

**Comment by MichaelTaylor3D** [comment]
We might need to talk about this further, there are some gotchas that make this request unworkable in my current understanding.
The issue is all about "timing". The main issue is that there is a twilight period between when the transaction is completed and when CADT knows its not up to date. So you cant really get an "isReady" in a single call. you need a minimum of 2 calls, because you need to check if the wallet is synced, then wait 5 seconds to give the CADT time to catch up and then check if the organization is synced. A instantaneous answer has to much opportunity to provide false positives.
